baseURL = "https://000095.xyz"
title = "Yet Another Toolbox"
theme = "hugo-notepadium"
copyright = "©2021 95+Live."

languageCode = "zh-cn"  # for the RSS generation
defaultContentLanguage = "en"

hasCJKLanguage = true

enableRobotsTXT = true

# Enable Disqus
#disqusShortname = "XXX"

# Google Analytics
#googleAnalytics = "UA-123-45"

[markup.highlight]
codeFences = true
noClasses = false

[markup.goldmark.renderer]
unsafe = true  # enable raw HTML in Markdown

[params]
style = "auto"  # default: auto. light: light theme, dark: dark theme, auto: based on system.
dateFormat = ""  # if unset, default is "2006-01-02"
readingTime = false  # show reading time after article date
logo = ""
slogan = "< Code is code />"
#license = "<a rel=license href=http://creativecommons.org/licenses/by-nc-sa/4.0/><img alt=Creative Commons License style=border-width:0 src=https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png /></a><br />This work is licensed under a <a rel=license href=http://creativecommons.org/licenses/by-nc-sa/4.0/>Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>."

#[params.assets]
#css = ["css/fonts.css"]

[params.comments]
enable = false  # En/Disable comments globally, default: false. You can always enable comments on per page.

[params.share]
enable = false  # En/Disable share globally, default: false. You can always enable share on per page.
addThisId = ""
inlineToolId = ""

[params.math]
enable = false # load math globally, default: false. You can always enable math on per page.
use = "katex"  # builtin: "katex", "mathjax".  default: "katex"

[params.syntax]
use = "none"  # builtin: "prismjs", "hljs". "none" means Chroma
theme = "github"
darkTheme = "dracula"

[params.profile]
  enable = true
  avatar = "https://img10.360buyimg.com/ddimg/jfs/t1/174761/32/17948/53448/60dfdb0aEf1700dfa/bb3bec3606eb7e8f.png"
  name = "Buy Me a Coffee"
  bio = "If our services are helpful to you, please **support** us."  # support markdown syntax
#  twitter = "GoHugoIO"  # https://twitter.com/XXX
#  github = "gohugoio"  # https://github.com/XXX

[params.nav]
showCategories = false       # /categories/
showTags = false             # /tags/

[[params.nav.custom]]
title = "#Service"
url = "/tags/service/"

[[params.nav.custom]]
title = "About"
url = "/about/"

#[[params.nav.custom]]
#title = "Hugo"
#url = "https://gohugo.io/"
